kind: Secret
apiVersion: v1
metadata:
  name: {{ template "helm-app.fullname" . }}
  labels:
    app: {{ template "helm-app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ range $key, $value := .Values.envConfig }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end}}
