apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: {{ template "helm-app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.web.metrics.service.type }}
  ports:
    - name: 'http-metrics'
      targetPort: {{ .Values.web.metrics.service.internalPort }}
      port: 9393
  selector:
    app: {{ template "helm-app.name" . }}
    release: {{ .Release.Name }}
