apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm-app.fullname" . }}
  labels:
    app: {{ template "helm-app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicasCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "helm-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "helm-app.name" . }}
        release: {{ .Release.Name }}
      # AUTOMATICALLY ROLL DEPLOYMENTS WHEN CONFIGMAPS OR SECRETS CHANGE
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/web-secret.yaml") . | sha256sum }}      
    spec:
      imagePullSecrets:
        - name: {{ .Values.web.image.pullSecret }}
      containers:
      # RAILS WEB APP
      - name: {{ .Chart.Name }}
        # https://stackoverflow.com/a/60054111
        image: "{{ .Values.web.image.repository }}:{{ template "helm-app.tag" . }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-config

#        ports:
#        - containerPort: {{ .Values.web.service.internalPort }}
#        volumeMounts:
#        - name: app-workdir
#          mountPath: "/myapp"
#        command: ["/bin/sh"]
#        args: ["-c", "cat tmp/pids/server.pid && rm -f tmp/pids/server.pid || true && bundle exec rails server -b 0.0.0.0 -p {{ .Values.web.service.internalPort }}"]
#      volumes:
#        - name: app-workdir
#          persistentVolumeClaim:
#            claimName: app-workdir-pvc
